# Site settings
title: neal machado
email: nealmachado12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  representational art by neal machado.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
youtube: nealmachado
instagram_username: nealm.art

# Build settings
markdown: kramdown
permalink: pretty
